### ISSUE TITLE
Please make it available for free!

### ISSUE THREAD

**Issue by Stargate38** [ivangrozny/TexTuring#5]
I went to the download page in hopes that this would be a free program, but unfortunately it doesn't seem so. Could you please make it available as a free download somewhere?

**Comment by ivangrozny** [comment]
Hello, I use the term Free software as we can found it here : https://en.wikipedia.org/wiki/Free_software 
If you want it, you can buy it 10€ on my website or compile the sources available on my github.
Hope this helps
